version: "2"
services:
   datalake-tdi:
       image: docker.skidata.net/datalake.tdi:0.0.1-SNAPSHOT
       mem_limit: 1024m
       ports:
           - "8080:8080"
       environment:
           SPRING_DATA_CASSANDRA_CONTACT_POINTS: "172.16.111.207"
           SPRING_DATA_CASSANDRA_PORT: "9042"