version: "2"
services:
   datalake-tdi:
       image: docker.skidata.net/datalake.tdi:0.0.1-SNAPSHOT
       mem_limit: 1024m
       ports:
           - "${PORT}:8080"
       environment:
           TDI_CASSANDRA_CONTACT_POINTS: "${TDI_CASSANDRA_CONTACT_POINTS}"
           TDI_CASSANDRA_PORT: "${TDI_CASSANDRA_PORT}"