version: "2"
services:
   datalake-tdi:
       image: docker.skidata.net/datalake.tdi:0.0.1-SNAPSHOT
       mem_limit: 1024m
       ports:
           - "${PORT}:8080"
       environment:
           TDI_CASSANDRA_CONTACT_POINTS: "172.27.80.144"
           TDI_CASSANDRA_PORT: "9042"