.catalog:
  name: "SKIDATA Datalake TDI"
  version: "0.0.1-SNAPSHOT"
  description: "Load and subscribe to data from TDI servers."
  minimum_rancher_version: v1.6.6
  questions: 

	- variable: TDI_CASSANDRA_PORT
	  description: "The port Cassandra CQL port, normally 9042"
	  label: "tdi.cassandra.port"
	  type: "int"
	  required: true
	  default: "9042"

	- variable: TDI_CASSANDRA_CONTACT_POINTS
	  description: "Comma separated list of host names or IPs where Cassandra is running"
	  label: "tdi.cassandra.contact-points"
	  type: "string"
	  required: true
	  
	- variable: PORT
	  description: "Exposed port"
	  label: "port"
	  type: "int"
	  required: true
	  default: "8088"

datalake-tdi:
  scale: 1
	  
