.catalog:
  name: "SKIDATA Datalake TDI"
  version: "0.0.1-SNAPSHOT"
  description: "Load and subscribe to data from TDI servers."
  minimum_rancher_version: v1.6.6
  questions: 

	- variable: SPRING_DATA_CASSANDRA_PORT
	  description: "See https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html"
	  label: "spring.data.cassandra.port"
	  type: "string"
	  required: true
	  default: "9042"

	- variable: SPRING_DATA_CASSANDRA_CONTACT_POINTS
	  description: "See https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html"
	  label: "spring.data.cassandra.contact-points"
	  type: "string"
	  required: true

datalake-tdi:
  scale: 1
	  
