version: "2"
services:
   cassandra:
       image: cassandra:3
       environment:
          MAX_HEAP_SIZE: 2G 
          HEAP_NEWSIZE: 256M
       
   datalake-tdi:
       image: docker.skidata.net/datalake.tdi:0.0.1-SNAPSHOT
       links: 
          - cassandra:db
       mem_limit: 1024m
       ports:
           - "${PORT}:8080"
       environment:
           TDI_CASSANDRA_CONTACT_POINTS: db
           TDI_CASSANDRA_PORT: 9042