version: "2"
services:
   cassandra:
       image: cassandra:3
       environment:
          MAX_HEAP_SIZE: "${CASSANDRA_MAX_HEAP_SIZE}"
          HEAP_NEWSIZE: "${CASSANDRA_HEAP_NEWSIZE}"
          
       
   datalake-tdi:
       image: docker.skidata.net/datalake.tdi:0.0.1-SNAPSHOT
       links: 
          - cassandra:db
       mem_limit: 1024m
       ports:
           - "${PORT}:8080"
       environment:
           TDI_CASSANDRA_CONTACT_POINTS: db
           TDI_CASSANDRA_PORT: 9042