.catalog:
  name: "SKIDATA Datalake TDI w/ Cassandra"
  version: "0.0.1-SNAPSHOT"
  description: "Load and subscribe to data from TDI servers. Bundle w/ Cassandra, use for test and demos."
  minimum_rancher_version: v1.6.6
  questions: 

   - variable: PORT
     description: "Exposed port for the Datalake rest services. The container port is 8080."
     label: "Exposed port"
     type: "int"
     required: true
     default: "8082"
     
   - variable: CASSANDRA_MAX_HEAP_SIZE
     description: "Limit the heap space as Cassandra uses quite a lot of memory(min 8GB) based on calculation, see https://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsTuneJVM.html#opsTuneJVM__tuning-the-java-heap"
     label: "Cassandra max heap space"
     type: "string"
     rewuired: true
     default: "2G"  

   - variable: CASSANDRA_HEAP_NEWSIZE
     description: "Limit the heap space chunks allocated by Cassandra"
     label: "Cassandra heap new size"
     type: "string"
     rewuired: true
     default: "256M"  

cassandra:
  scale: 1
datalake-tdi:
  scale: 1
     
